### ISSUE TITLE
Integration tests don't seem to run

### ISSUE THREAD

**Issue by token-cjg** [ceceppa/godot-gut-ci#4]
I discovered in testing that when using this test folder structure:

```
test
-unit
--test_1.gd
-integration
--test_2.gd
```

and using this as action:

```
name: "godot gut test"
on: push

jobs:
  execute-gut:
    name: Run GUT tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker test
        uses: ceceppa/godot-gut-ci@master
        with:
          godot_version: 3.2.1 # uses godot 3.2.1
          unit_test: res://test/unit
          integration_test: res://test/integration
```

that only the unit tests were executed; the integration tests were ignored.
